image:
  file: .gitpod.Dockerfile

tasks:
- init: echo 'setup workspace' # runs during prebuild
  command: |
     ln -fs ~/swift-4.0.2/ /workspace/
     echo "build with: mkdir build && cd build && qmake .. && make"

