extraction:
  cpp:
    prepare:
      packages:
        - qt5-default
        - libqt5sql5-sqlite
        - libswiften-dev
        - qtdeclarative5-dev
        - qml-module-qtquick2
        - qml-module-qtquick-controls
    configure:
      command:
      - "mkdir _lgtm_build_dir"
      - "cd _lgtm_build_dir"
      - "qmake .. DEFINES+=TRAVIS"

