extraction:
  cpp:
    prepare:
      packages:
        - qt5-default
        - libqt5sql5-sqlite
        - qtdeclarative5-dev
        - qml-module-qtquick2
        - qml-module-qtquick-controls
        - libssl-dev
    after_prepare:
      - pwd
      - wget https://swift.im/downloads/releases/swift-4.0.2/swift-4.0.2.tar.gz
      - tar -xf swift-4.0.2.tar.gz
      - cd swift-4.0.2
      - sed -i -E "s/(env\[\"BOOST_BUNDLED\"\] = True)/\1\n\1/" BuildTools/SCons/SConstruct
      - ./scons Swiften
    configure:
      command:
        - pwd
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - qmake .. DEFINES+=TRAVIS

