language : cpp
compiler: gcc
os: linux
dist: xenial

install:
    - sudo echo "deb http://de.archive.ubuntu.com/ubuntu/ eoan main restricted" >> /etc/apt/sources.list
    - sudo echo "deb http://de.archive.ubuntu.com/ubuntu/ eoan universe" >> /etc/apt/sources.list
    - sudo apt-get -qq update
    - sudo apt-get -qq install qt5-default libqt5sql5-sqlite qtdeclarative5-dev qml-module-qtquick2 qml-module-qtquick-controls lcov

    - sudo apt-get install asciidoctor plantuml graphviz
    - sudo apt-get install xvfb ejabberd
    - wget -q https://swift.im/downloads/releases/swift-4.0.2/swift-4.0.2.tar.gz && tar -xf swift-4.0.2.tar.gz && cd swift-4.0.2 && /bin/bash scons -j 4 Swiften && cd ..

script:
    # standard x86 build
    #- mkdir -p buildx86
    #- cd buildx86
    #- qmake .. DEFINES+=TRAVIS
    #- make
    #- cd ..

    # testing. build and run
    - ${TRAVIS_BUILD_DIR}/scripts/travis/testing.sh

    # create architecture
    - cd ${TRAVIS_BUILD_DIR}/doc/architecture/images/
    - plantuml *.plantuml
    - cd ..
    - asciidoctor index.adoc
    - cd ${TRAVIS_BUILD_DIR}


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN_REPO
  keep_history: true
  local_dir: ${TRAVIS_BUILD_DIR}/doc/architecture/
  on:
    branch: master

